const PLAYER = {
    STARTING_POSITION_X: 400,
    STARTING_POSITION_Y: 404,

    MAX_SPEED: 400,

    HEAD: {
        STARTING_POSITION_X: 396,
        STARTING_POSITION_Y: 360
    }
};

const BAR = {
    BORDER_POSITION_X: 0,
    BORDER_POSITION_Y: 470,
};

const BULLET = {
    SPEED: 400,
    SPACING: 450
};

const EXPLOSION = {
    WHITE_SPEED: 12,
    RED_SPEED: 30
};